version '2'

services:
  # PostgreSQL as databse
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER={{cookiecutter.db_user}}
      - POSTGRES_PASSWORD={{cookiecutter.db_pwd}}
      - POSTGRES_DB={{cookiecutter.db_name}}
    ports:
      - "5432:5432"
      

  # Django web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./run_web.sh
    volumnes: .:/web_app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  # Node container
  #node:
  #  build: 
  #    context: .
  #    dockerfile: Dockerfile.node
  #  hostname: node
  #  volumes:
  #    - ./{{cookiecutter.project_name}}/frontend/:/web_app/
  #  links:
  #    - web
  #  ports:
  #    "3000:3000"
  
      
